apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointservice
  labels:
    app: pointservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointservice
  template:
    metadata:
      labels:
        app: pointservice
    spec:
      containers:
        - name: pointservice
          image: "username/pointservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
